# Site settings
title: Center for Aquatic Biology and Aquaculture 
email: caba.ucdavis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Center for Aquatic Biology and Aquaculture (CABA) was established to provide leadership, focus, and support to University of California Davis researchers in addressing problems associated with California’s cultured and wild aquatic biological resources.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caba.ucdavis.edu" # the base hostname & protocol for your site

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap
